[package]
name = "compressor-dwi"
version = "0.1.0"
edition = "2024"
description = "Dual-wire async serial protocol driver for compressor drivers"
repository = "https://github.com/phycrax/compressor-dwi"
license = "MIT OR Apache-2.0"
categories = ["embedded", "no-std", "asynchronous"]
keywords = ["compressor", "driver", "hvac"]

[features]
defmt = ["dep:defmt"]

[dependencies]
embedded-hal-async  = { workspace = true }
embedded-io-async   = { workspace = true }
defmt               = { workspace = true, optional = true }

embassy-futures = "0.1.2"
 
